############# English navigation ##############

# main menu
[[main]]
name = "GC Cloud One: Aurora"
url = "/"
weight = 1
identifier = "home"

[[main]]
name = "Platform"
url = "/platform"
weight = 5

  [[main]]
  name = "Proposal"
  parent = "Platform"
  url = "/proposal"
  weight = 1

  [[main]]
  name = "Vision"
  parent = "Platform"
  url = "/vision"
  weight = 3

  [[main]]
  name = "Components"
  parent = "Platform"
  url = "/components"
  weight = 5

[[main]]
name = "Contact us"
url = "/contact"
weight = 10

[[main]]
name = "Get involved"
url = "/get-involved"
weight = 15

[[breadcrumb]]
name = "GC Cloud One"
url = "https://gccloudone.ca"
weight = 1
